# Generated by Django 3.0.5 on 2020-04-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('img', models.ImageField(max_length=250, upload_to='carousel/')),
                ('position', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Слайдер на главной',
                'verbose_name_plural': 'Слайдер на главной',
                'ordering': ('position',),
            },
        ),
    ]
