# Generated by Django 3.0.5 on 2020-04-30 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200430_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Menu'),
        ),
    ]
