# Generated by Django 3.0.5 on 2020-05-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_page_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='menu',
        ),
        migrations.AddField(
            model_name='page',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('menu_top', 'Пункт меню в верхней части'), ('menu_footer', 'Пункт меню в подвале сайта'), ('page_link', 'Статическая страница'), ('simple_link', 'Обычная ссылка')], default='simple_link', max_length=50),
        ),
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
