# Generated by Django 3.0.5 on 2020-05-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200502_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('position',), 'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterField(
            model_name='page',
            name='is_menu_footer',
            field=models.BooleanField(default=False, verbose_name='Показывать в нижнем меню'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_menu_top',
            field=models.BooleanField(default=False, verbose_name='Показывать в верхнем меню'),
        ),
    ]
