# Generated by Django 3.0.5 on 2020-04-24 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.SlugField(max_length=128)),
                ('type', models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('boolean', 'True / False'), ('float', 'Float'), ('date', 'Date'), ('option', 'Option')], default='text', max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('widget_type_display', models.CharField(choices=[('checkbox_list', 'Чекбоксы'), ('select_list', 'Селектор'), ('slider_input', 'Ползунок')], default='checkbox_list', max_length=50)),
            ],
            options={
                'verbose_name': 'Атрибут продукта',
                'verbose_name_plural': 'Атрибуты продуктов',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeOptionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('code', models.SlugField(max_length=128)),
            ],
            options={
                'verbose_name': 'Группа параметров атрибута',
                'verbose_name_plural': 'Группа параметров атрибута',
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.ProductAttribute')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category')),
            ],
            options={
                'verbose_name': 'Атрибуты/Категории',
                'verbose_name_plural': 'Атрибуты/Категории',
                'ordering': ['attribute', 'category'],
                'unique_together': {('attribute', 'category')},
            },
        ),
        migrations.AddField(
            model_name='productattribute',
            name='category',
            field=models.ManyToManyField(related_name='attributes', through='catalog.ProductAttributeCategory', to='catalog.Category'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='option_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.ProductAttributeOptionGroup'),
        ),
        migrations.CreateModel(
            name='ProductAttributeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=255)),
                ('show_value', models.CharField(blank=True, max_length=255, null=True)),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.ProductAttributeOptionGroup')),
            ],
            options={
                'verbose_name': 'Опция атрибута',
                'verbose_name_plural': 'Опции для атрибутов',
                'ordering': ('option',),
                'unique_together': {('group', 'option')},
            },
        ),
    ]
