# Generated by Django 3.0.5 on 2020-05-02 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoModuleFilterUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название страницы')),
                ('url', models.CharField(max_length=255, verbose_name='Сгенерированный url')),
                ('has_product', models.BooleanField(default=False, verbose_name='Наличие товара')),
                ('h1', models.CharField(blank=True, max_length=255, null=True, verbose_name='h1 заголовок')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='meta title')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='meta description')),
                ('keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='meta keywords')),
                ('seo_text', models.TextField(blank=True, null=True, verbose_name='SEO текст')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_urls', to='catalog.Category')),
            ],
            options={
                'verbose_name_plural': 'Сгенерированные страницы',
            },
        ),
    ]
