# Generated by Django 3.0.5 on 2020-05-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_seomodulefilterurls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'ordering': ['code'], 'verbose_name': 'Атрибут продукта', 'verbose_name_plural': 'Атрибуты продуктов'},
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='code',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
