# Generated by Django 3.0.5 on 2020-05-02 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200502_1754'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeoModuleFilterUrls',
            new_name='SeoModuleFilterUrl',
        ),
    ]
