# Generated by Django 3.0.5 on 2020-05-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_productrecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seomodulefilterurl',
            name='url',
            field=models.CharField(max_length=1024, verbose_name='Сгенерированный url'),
        ),
    ]
