# Generated by Django 3.0.5 on 2020-06-26 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20200506_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitemapFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitemap_filter', to='catalog.ProductAttribute')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitemap_filter', to='catalog.Category')),
            ],
        ),
    ]
