# Generated by Django 3.0.5 on 2020-07-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_quicklink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quicklink',
            options={'verbose_name': 'Быстрая ссылка', 'verbose_name_plural': 'Быстрые ссылки'},
        ),
        migrations.AddField(
            model_name='productattribute',
            name='prefix_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productattributeoption',
            name='genitive_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
