# Generated by Django 3.0.5 on 2020-07-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20200705_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributeoption',
            name='genitive_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
