# Generated by Django 3.0.5 on 2020-04-25 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200424_1214'),
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_reference', models.SlugField(max_length=128, verbose_name='Line Reference')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_excl_tax', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='basket.Basket')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_lines', to='catalog.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Строка корзины',
                'verbose_name_plural': 'Строки корзины',
                'ordering': ['date_created', 'pk'],
                'unique_together': {('basket', 'line_reference')},
            },
        ),
    ]
